<div class="jumbotron">
    <h2>Refactor The ZF2 ServiceLocatorAwareInterface<br>Out Of A Controller With PhpStorm</h2>
</div>
This repository is the code example for the Soliant Consulting blog post of the same name. You can find it at <a href=""www.soliantconsulting.com">www.soliantconsulting.com</a>
<div>
    <h3><a href="<?= $this->url('application-details') ?>">Failing Controller</a> </h3>
    <h3><a href="<?= $this->url('application-details-refactored') ?>">Refactored Controller</a></h3>
</div>
